{{- range $name, $config := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.containerName }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $config.containerName }}
    {{- include "bus-booking.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $config.containerName }}
  template:
    metadata:
      labels:
        app: {{ $config.containerName }}
    spec:
      serviceAccountName: bus-booking
      containers:
        - name: {{ $config.containerName }}
          image: {{ $config.image }}:{{ $config.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $config.port }}
          env:
            {{- /* Global env variables */ -}}
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- /* Service-specific env variables */ -}}
            {{- if $config.env }}
            {{- range $key, $value := $config.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
{{- end }}