apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bus-booking.fullname" . }}-secret
  labels:
    {{- include "bus-booking.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.env.global.JWT_SECRET | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bus-booking.fullname" . }}-db-secret
  labels:
    {{- include "bus-booking.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.env.database.DB_PASSWORD | b64enc | quote }}