apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-internal
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: user-internal.{{ .Values.domain | default "cluster.local" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trip-service-internal
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: trips-internal.{{ .Values.domain | default "cluster.local" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: trip-service
                port:
                  number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-service-internal
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: bookings-internal.{{ .Values.domain | default "cluster.local" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-service-internal
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: payments-internal.{{ .Values.domain | default "cluster.local" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8084
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-service-internal
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
    - host: templates-internal.{{ .Values.domain | default "cluster.local" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: template-service
                port:
                  number: 8083
