# Booking Service Specific Configuration
services:
  bookingService:
    enabled: true
    name: booking-service
    port: 8082
    targetPort: 8082
    image:
      repository: npkhang22/bb-booking-service
      tag: booking-service-b905274
    env:
      SERVER_PORT: "8082"
      SERVICE_NAME: "booking-service"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Disable other services for this deployment
  userService:
    enabled: false
  gatewayService:
    enabled: false
  tripService:
    enabled: false