# Trip Service Specific Configuration
services:
  tripService:
    enabled: true
    name: trip-service
    port: 8081
    targetPort: 8081
    image:
      repository: npkhang22/bb-trip-service
      tag: trip-service-b905274
    env:
      SERVER_PORT: "8081"
      SERVICE_NAME: "trip-service"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Disable other services for this deployment
  userService:
    enabled: false
  gatewayService:
    enabled: false
  bookingService:
    enabled: false