# User Service Specific Configuration
services:
  userService:
    enabled: true
    name: user-service
    port: 8080
    targetPort: 8080
    image:
      repository: npkhang22/bb-user-service
      tag: user-service-3ab4224
    env:
      SERVER_PORT: "8080"
      SERVICE_NAME: "user-service"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  # Disable other services for this deployment
  gatewayService:
    enabled: false
  tripService:
    enabled: false
  bookingService:
    enabled: false