apiVersion: v1
kind: ServiceAccount
metadata:
  name: bus-booking
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bus-booking.labels" . | nindent 4 }}
automountServiceAccountToken: true