{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.containerName }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $config.containerName }}
    {{- include "bus-booking.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $config.containerName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
{{- end }}